name: mosdef 
channels:
  - conda-forge
dependencies:
  - python=3.12.13
  - boltons=26.0.0
  - numba=0.65.1
  - numpy=2.2.6
  - sympy=1.14.0
  - unyt=3.1.0
  - lark=1.3.1
  - lxml=6.1.1
  - intermol=0.1.2
  - mdtraj=1.11.1
  - pydantic=2.13.4
  - networkx=3.6.1
  - nglview=4.0.1
  - pytest=9.1.1
  - garnett=0.7.1
  - openff-toolkit-base=0.18.1
  - cgsmiles
  - openmm=8.5.2
  - gsd=5.0.1
  - freud=3.5.0
  - parmed=4.3.1
  - packmol=21.2.1
  - pycifrw=5.0.1
  - rdkit=2026.03.3
  - requests=2.34.2
  - requests-mock=1.12.1
  - scipy=1.18.0
  - treelib=1.7.1
  - matplotlib=3.11.0
  - ipywidgets=8.1.8
  - ele=0.2.0
  - pandas=2.3.3
  - symengine=0.14.0
  - python-symengine=0.14.1
  - py3Dmol=2.5.4
  - hoomd=7.1.0
  - jupyterlab
  - pip:
      - git+https://github.com/chrisjonesBSU/gmso.git@cecam
      - git+https://github.com/mosdef-hub/foyer.git@main
      - git+https://github.com/mosdef-hub/forcefield-utilities.git@main
      - git+https://github.com/mosdef-hub/mbuild.git@develop
